### ISSUE TITLE
homedecor:chair and fly

### ISSUE THREAD

**Issue by Ombridride** [VanessaE/homedecor_modpack#182]
Hi Vanessae,

I've found a bug with the latest version of homedecor and the latest dev version of minetest.

When im sit on a homedecor:chair, if i jump, i can fly !

**Comment by kilbith** [comment]
I can't reproduce that.

**Comment by Ombridride** [comment]
I tried he bug in local and i don't fly, but my character is under the "dirt level" of the chair.
Like you said, i think the problem is our subgame MinetestForFun_game (available here : https://github.com/Ombridride/minetest-minetestforfun-server)

**Comment by Ombridride** [comment]
In my server i still have the problem, the irfurn code doesn't reproduce the homedecor:chair/banc fly problem. So i will remove the chair/banc code and repalce it by the irfurn code... 

It's not the best way, i suppose, because now the player don't have anymore the "sit" animation, But i haven't any other idea...

Maybe let this issue open if another server met this problem ?

**Comment by vitaminx** [comment]
Here's how to reproduce a "flying bug": right click on a chair or bench to sit, then move quickly before your character is moved to the chair/bench. The player keeps his/her momentum and flies around in a sitting position! Quite funny bug tho ;)

**Comment by kilbith** [comment]
@vitaminx It's a known bug in the engine. I've mostly avoided it by blocking the moving keys while clicking but it remains not 100% reliable.

**Comment by VanessaE** [comment]
This feature has been disabled in current homedecor HEAD until both homdecor and the engine code can come to some kind of agreement on handling of the "sit" function.
