### ISSUE TITLE
Issue after update

### ISSUE THREAD

**Issue by giammi** [VanessaE/homedecor_modpack#194]
Hello,
did a git pull. After that when restarting minetest I get a lot of "unknown node" in my world. Some items disappeared to. They are in the inventory as "unknown item"

Error messages when starting up are like e.g. Item "homedecor:door_wood_plain_bottom_right" not defined

Is there a way to get back to a previous version or what needs to be done? Thanks for your help.

rgds
Giammi

**Comment by VanessaE** [comment]
Sounds like you didn't install the update correctly.  That item resolves correctly in the current code when I use  `/giveme` to acquire it.
