### ISSUE TITLE
Texture bug on the opened book

### ISSUE THREAD

**Issue by kilbith** [VanessaE/homedecor_modpack#195]
Darker on top of pages whereas the same colour is defined for the pages sides (clearer).

![sdf](https://cloud.githubusercontent.com/assets/7883281/6318062/dccbebcc-ba7b-11e4-88da-3e281645673a.jpg)

**Comment by VanessaE** [comment]
it's a model glitch.  fixed with d009cdd649367716a42593b226242ec41b4087cf
