### ISSUE TITLE
Woofers

### ISSUE THREAD

**Issue by YvesLevier** [VanessaE/homedecor_modpack#208]
12:44:03 - YvesLevier : 12:35:14 - YvesLevier : deezl: i mean i wish speakers with speaker drivers to be seen on speakers appearance
12:44:03 - YvesLevier : 12:35:15 - deezl : better to stop the server first
12:44:03 - YvesLevier : 12:35:39 - xenkey : not at all
12:44:03 - YvesLevier : 12:35:45 - xenkey : it'll work just fine
12:44:03 - YvesLevier : 12:36:10 - deezl : YvesLevier, so you want speakers with the covers off...
12:44:03 - YvesLevier : 12:36:21 - YvesLevier : YESS
12:44:03 - YvesLevier : 12:36:23 - YvesLevier : ;)
12:44:03 - YvesLevier : 12:36:27 - deezl : you may have to create your own textures for that
12:44:03 - YvesLevier : 12:36:39 - deezl : or beg VanessaE to add those in :D
12:44:03 - YvesLevier : 12:36:51 - deezl : that would be kinda neat
12:44:03 - YvesLevier : 12:38:16 - YvesLevier : Will.  Thx :)
12:44:45 - YvesLevier : plz?

**Comment by kilbith** [comment]
Next time make a clearer, straightforward request instead of copy-pasting a chit-chat. Our time is too precious for futilities...

**Comment by VanessaE** [comment]
Will do later after the other model work is done.

**Comment by YvesLevier** [comment]
Noted

**Comment by YvesLevier** [comment]
Acknoleged, thx.

**Comment by VanessaE** [comment]
65aa834821c0d71cdd23f8790b232a1d7ba0e61e et al.
