### ISSUE TITLE
Request for Wall Sconce

### ISSUE THREAD

**Issue by deezl** [VanessaE/homedecor_modpack#219]
was just thinking with how nicely detailed a lot of the items in Homedecor have become, a nice wall sconce would be cool. Something like: http://designsenselighting.com/wp-content/uploads/2011/12/Wall-Sconces-with-Candles.jpg

**Comment by VanessaE** [comment]
Added into the main TODO (#198)

**Comment by VanessaE** [comment]
implemented with commit 79b5c94f6c15749ca856b9392cd7ae8d9c412474 et al.

**Comment by deezl** [comment]
Yay! Thanks Vanessa, can't wait to see it!
