### ISSUE TITLE
Marble

### ISSUE THREAD

**Issue by Wolfboyjr** [VanessaE/homedecor_modpack#233]
:palm_tree: When i want to make dyed bathroom/kitchen tiles i have to make marble ( go through the process of getting gravel, making tar base, cooking it, finding clay, and crafting it) I can't use the marble i mine out of the ground, and they have very similar textures so it is hard to tell which is which and it just adds a lot of confusion and extra time.... Thanks for your concern :palm_tree:

**Comment by VanessaE** [comment]
What's the node name for the marble you're getting out of the ground?  (on PC, press F5 and then point at the object and the debug display will tell you what it is)

**Comment by Wolfboyjr** [comment]
i don't see the node name when i do the F5 thing :ideograph_advantage: 
:cactus: ill be off for a few hours, so ill get back to you later

**Comment by VanessaE** [comment]
It's morestones:marble from CWz's morestones mod.  Found some on the server in question.  Anyway homedecor and building_blocks have been adjusted to use appropriate groups for marble and tar, and an appropriate pull request has been made against morestones.
