### ISSUE TITLE
Text not Appearing on Newly Placed Locked Signs

### ISSUE THREAD

**Issue by LazyJ** [VanessaE/homedecor_modpack#234]
**HomeDecor Commit:** b90c03c, 2015_04_22
**Minetest Engine Commit:** dev version [ac6efa2](https://github.com/minetest/minetest/commit/ac6efa25390cbe522ac4fb3efc68c22081a023c4), 2015_04_22 and Minetest-0.4.12 stable
**Minetest_Game Commit:** [d0070f2](https://github.com/minetest/minetest_game/commit/d0070f2b1ad87bca10262a3b1efff7497049ca66), 2015_04_22

When a locked sign is placed on the west side of a wall, the text is displayed on the face of the locked sign.

When a locked sign is placed on the east side of a wall, the text is displayed in the air to the south of the locked sign.

When a locked sign is placed on the north or south side of a wall, the text is not displayed at all.

I was able to come up with a fix. It may not be text-book perfect but it works.

Starting at line 556 of sign_lib/init.lua:

Currently:
```lua
if signnode.name == "default:sign_wall" then
sign_info = signs_lib.regular_wall_sign_model.textpos[minetest.get_node(pos).param2 + 1]
else
```

Fix:
```lua
if signnode.name == "default:sign_wall"
or signnode.name == "locked_sign:sign_wall_locked" then
sign_info = signs_lib.regular_wall_sign_model.textpos[minetest.get_node(pos).param2 + 1]
else
```

**Comment by VanessaE** [comment]
Good catch, not sure how I missed that.  c485a3a
