### ISSUE TITLE
Undeclared global variable "screwdriver" in carbon

### ISSUE THREAD

**Issue by svenXY** [VanessaE/homedecor_modpack#275]
Hi,

carbon fails to start with your mod with the following error:

Undeclared global variable "screwdriver" accessed at .../.minetest/mods/homedecor_modpack/signs_lib/init.lua:14 

Is this something me (or you) could fix easily

**Comment by VanessaE** [comment]
This is a problem in the Carbone game.

**Comment by svenXY** [comment]
OK, thanks for the quick reply
