### ISSUE TITLE
Gold coin and similar name

### ISSUE THREAD

**Issue by Ombridride** [VanessaE/homedecor_modpack#280]
Hi,

Just to point that, maybe it's not a bad idea to specified the use of this coins in the description like that ?

https://github.com/Ombridride/minetest-minetestforfun-server/commit/a615ae3048ad3f6dab60f9eaf0759158c1c3706e

**Comment by VanessaE** [comment]
Good idea.  f0da8f3

As for other coins, I could add support for them if someone can provide me a list of item names from the various money mods and elsewhere -- so long as doing so won't mess up basic gameplay.
