### ISSUE TITLE
No Bucket Returned when Used on Well and Hot Bar is Full to the Left of the Bucket

### ISSUE THREAD

**Issue by LazyJ** [VanessaE/homedecor_modpack#281]
**Minetest Engine:**  [502e40a](http://github.com/minetest/minetest/commit/502e40a649137461947c36ea52205f058f81296f)
**Minetest_Game:**  [f09ae11](http://github.com/minetest/minetest_game/commit/c4fb5bd385961e1ed2da9d0826af13cadde58265)
**HomeDecor:**  81f3c96

Vanilla setup, test world dedicated soley to HomeDecor.

If the hot bar is full to the left of a **single** *(not a stack of buckets)* empty, wield-hand bucket, the bucket is deleted and no water bucket is returned when used on the well.

**Comment by VanessaE** [comment]
6bf41d0
