### ISSUE TITLE
Circular stairs buggy 

### ISSUE THREAD

**Issue by israuor** [VanessaE/homedecor_modpack#289]
Is it just me, or is there something wrong with the circular stairs. When I climb up I fall down somewhere in the middle of the stairs. 
Another issue: when I place two of them on top of each other and remove them again, I'll get out 3.

**Comment by israuor** [comment]
Sorry, meant spiral staircases

**Comment by VanessaE** [comment]
The falling issue is actually an engine bug with collision handling.

About the count issue, I get back exactly the number I placed, but on place they aren't being deducted from the stack if you place one on top of another.  That should be fixed now.

**Comment by israuor** [comment]
Yesss. Thx
