### ISSUE TITLE
craft_guide - mod displays a bunch of duplicate recipes on some items

### ISSUE THREAD

**Issue by tchncs** [VanessaE/homedecor_modpack#297]
![bildschirmfoto vom 2015-10-05 14-21-31](https://cloud.githubusercontent.com/assets/10698140/10280409/50e75b20-6b6d-11e5-959c-c85002558d0b.png)
We just saw, that the Craftguide Mod displays thousands of duplicate recipes on the 
```standing lamp (white)``` and ```table lamp (white)```.

**Comment by t4im** [comment]
I'd say that is something to report to the crafting guide mod then.

**Comment by tchncs** [comment]
The crafting guide just grap recipes from all mods and make them visual - so i think its a problem from homedecor... .

**Comment by t4im** [comment]
The crafting guide looks through the registry to display them. And apparently does that wrong.

Homedecor registers these lamps correctly (theres basically nothing you could do wrong besides registering it 200k times, which i checked, doesn't happen).
This just leaves the crafting guide or the engines crafting recipe handling. I'd say crafting guide is more likely.

Please open an issue there.

**Comment by VanessaE** [comment]
This is not a Homedecor bug, as it works fine when displayed in e.g. Unified Inventory's Crafting Guide. The problem is, as t4im says, either in the crafting guide mod you're using, or in the engine.
