### ISSUE TITLE
Unable to place sideways signs.

### ISSUE THREAD

**Issue by kaeza** [VanessaE/homedecor_modpack#298]
Noting this here so it doesn't get lost.

One user reported being unable to place sideways signs like this:
![image](https://cloud.githubusercontent.com/assets/2388420/10413914/8e0dc1fe-6f93-11e5-8a97-1fbd5c7b5bc3.png)

It was possible before he updated to latest homedecor.

It is possible that the known sign text yaw problem is also in related changes (probably changed node rotation/placement code).

User reports previous homedecor version is from around March 2015.

**Comment by VanessaE** [comment]
I can also reproduce this, but I believe it's because now the engine is handling the node's rotation.  A sign can still be placed against a block, perpendicular to the desired surface, and then that block can be removed.  That will ive the effect the reporting user wanted.

**Comment by redblade7** [comment]
I am still able to make double-sided color signs, it's only the wooden ones that don't work.

**Comment by VanessaE** [comment]
signs_lib has been split off into its own repository, here:

https://github.com/VanessaE/signs_lib

Please re-open this issue over on that repository.
