### ISSUE TITLE
Signs created with older versions of homedecor have text facing wrong direction.

### ISSUE THREAD

**Issue by kaeza** [VanessaE/homedecor_modpack#299]
Possibly related to #298.

**Comment by VanessaE** [comment]
There was a rotation change I did a while back to make wooden wall signs match the behavior of the default minetest_game signs.  The intent was to make it possible to just drop signs_lib into an existing world that has never had it before, and have it "just work" (which indeed it does).

This had the negative side effect of screwing up the rotation of existing signs that had been altered by signs_lib at some point.

**Comment by kaeza** [comment]
>So this is a "wontfix"? :(

Definitely not. This should be fixed, but I am [compiling](https://xkcd.com/303/).

**Comment by VanessaE** [comment]
signs_lib has been split off from homedecor and can be found here:  https://github.com/VanessaE/signs_lib

This and #298 should be addressed there.
