### ISSUE TITLE
Item entity loading causes lag

### ISSUE THREAD

**Issue by CraigyDavi** [VanessaE/homedecor_modpack#301]
After a little while of debuging I found that there were awful lag spikes when players moved close to areas with lots of itemframes. I later found that the abm [here](https://github.com/VanessaE/homedecor_modpack/blob/master/itemframes/init.lua#L206) was the most likely cause of it.

I suggest that either update_items gets optimised or there should be a setting such as `itemframes.clearobjects_update` which can be set to true if you require this feature.

**Comment by VanessaE** [comment]
You are experiencing either ABM "catch-up" lag or entity reload lag.  

Try updating to a current dev/daily build and add "catch_up = false" to that ABM definition.  Let me know if it helps.

**Comment by CraigyDavi** [comment]
I'm using the current daily build and didn't notice this problem before so https://github.com/minetest/minetest/pull/3248 is probably to blame. I'll add that line now and see if it works.

**Comment by CraigyDavi** [comment]
Ok, adding catch_up = false didn't seem to help, at least not by any noticeable amount.

**Comment by CraigyDavi** [comment]
Actually I'm still noticing issues when removing the ABM altogether... It looks more like the loading of the entities in the first place is the problem.

**Comment by CraigyDavi** [comment]
Ok, I have removed the mod and when moving close to the unknown entities there are still problems caused.. maybe there's something in the metadata?

**Comment by VanessaE** [comment]
Ya got me :smile:  I can only assume it's simple entity (re)load lag.  Even undefined, they're still stored "in the map".
