### ISSUE TITLE
Placing items on slim surface

### ISSUE THREAD

**Issue by CodePhase** [VanessaE/homedecor_modpack#305]
Hello,

I know that a node like 'Wood Table Piece' is a node with non-visible area on its top above the visible texture surface, but is there a way to place items on it without it looking like it's flying?  I doubt so, but my candlesticks look pretty dumb hovering way above the dining room table I'm trying to build :-)
![flyingcandlesticks](https://cloud.githubusercontent.com/assets/14020204/12520131/c030b62c-c110-11e5-85c2-861389f7ca8a.png)

Thanks!

**Comment by VanessaE** [comment]
There's no way to do that in minetest at present.  You can fake it by placing the tabletop one node lower and then rotating it with the screwdriver, then placing the candlestick on top of that.  Won't work if you need something under the tabletop node though, but it might work for the image you've displayed here, where there are "table legs" only at the corners of the area.

**Comment by CodePhase** [comment]
Thanks for the suggestion.  I removed the table legs and did what you've described and it looks fine.  Now I have a magical floating table :-)

**Comment by kaeza** [comment]
Now that Minetest supports meshnodes, table legs and tops could be combined into a mesh to avoid this problem.

**Comment by CodePhase** [comment]
@kaeza that's interesting.  I've never done any work in Lua before but perhaps I can look to see if this would help.  However, how would this work with just a tabletop node that is not attached to the table legs?
