### ISSUE TITLE
Pixel/particle errors on water from faucet

### ISSUE THREAD

**Issue by greencopper** [VanessaE/homedecor_modpack#306]
Hi

Please see shot below.

![skaermbillede - 20-02-2016 - 00 06 53](https://cloud.githubusercontent.com/assets/1302896/13191741/21b22442-d766-11e5-9328-051aeeee1f45.png)

Kind regards

**Comment by VanessaE** [comment]
This was due to an engine/client bug and was fixed quite a while ago.
